# Generated by Django 4.2.10 on 2024-03-03 14:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(max_length=100)),
                ('device_name', models.CharField(max_length=100)),
                ('port_name', models.CharField(max_length=100)),
                ('port_status', models.CharField(max_length=100)),
                ('region', models.CharField(choices=[('R1', 'R1'), ('R2', 'R2'), ('R3', 'R3'), ('R4', 'R4')], max_length=15)),
                ('register_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
